# Generated by Django 2.1.5 on 2020-11-04 12:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201026_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='正在想'),
        ),
    ]
