# Generated by Django 2.1.5 on 2020-10-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_likes_like_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='is_like',
        ),
    ]
