# Generated by Django 2.1.5 on 2020-10-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20201026_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes_count',
            name='like_count',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
